#!/bin/bash

SSHD_CONFIG=/etc/ssh/sshd_config

HOME=/root
PORT=${PORT:-22}
LISTEN_ADDRESS=${LISTEN_ADDRESS:-127.0.0.1}

SSH_USER=${SSH_USER:-root}
SSH_PASSWD=${SSH_PASSWD:-np}

[ "$SSH_PASSWD" != "np" ]   && echo "$SSH_USER:$SSH_PASSWD" | chpasswd

[ "$SSH_USER" != "root" ]   && HOME=/home/$SSH_USER \
                            && useradd $SSH_USER -s "/bin/bash" -m -d /home/$SSH_USER \
                            && usermod -aG sudo "$SSH_USER" \
                            && echo "$SSH_USER ALL=(ALL) NOPASSWD:ALL" | tee -a /etc/sudoers

[ ! -z "$SSH_KEY" ]         && mkdir -p $HOME/.ssh \
                            && echo "$SSH_KEY" | tee $HOME/.ssh/authorized_keys \
                            && chmod 600 $HOME/.ssh/authorized_keys


sed -i "s/#\?Port [0-9]\+/Port $PORT/g" $SSHD_CONFIG
sed -i "s/#\?ListenAddress [0-9\.]\+/ListenAddress $LISTEN_ADDRESS/g" $SSHD_CONFIG
sed -i "s/#\?PubkeyAuthentication \(yes\|no\)/PubkeyAuthentication $PUBKEY_AUTHENTICATION/g" $SSHD_CONFIG
sed -i "s/#\?PasswordAuthentication \(yes\|no\)/PasswordAuthentication $PASSWD_AUTHENTICATION/g" $SSHD_CONFIG
sed -i "s/#\?PermitEmptyPasswords \(yes\|no\)/PermitEmptyPasswords $PERMIT_EMPTY_PASSWD/g" $SSHD_CONFIG
sed -i "s/#\?PermitRootLogin \(yes\|no\|prohibit-password\)/PermitRootLogin $PERMIT_ROOT_LOGIN/g" $SSHD_CONFIG

exec "$@"
